DAY 3 ASSIGNMENT 

 **QUESTION 1 :** 
 
 **Create a numpy array starting from 2 to 50 with a stepsize of 3.**

In [27]:
import numpy as np

arr = np.arange(2, 51 ,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


 **QUESTION 2 :** 
 
 **Accept two lists of 5 elements each from the user.Convert them to numpy arrays.Concatenate these arrays and print it.Also sort these arrays and print it.**

In [30]:
import numpy as np

lst_1 = []
lst_2 = []

for i in range(5) :
  x = int(input("Enter the value for list 1 :"))
  lst_1.append(x)

print()

for i in range(5) :
  x = int(input("Enter the value for list 2 :"))
  lst_2.append(x)

arr_1 = np.array(lst_1)
arr_2 = np.array(lst_2)

arr = np.concatenate((arr_1 , arr_2))
print()
print()
print("Concatenated array : " , np.sort(arr))

Enter the value for list 1 :3
Enter the value for list 1 :23
Enter the value for list 1 :54
Enter the value for list 1 :14
Enter the value for list 1 :52

Enter the value for list 2 :52
Enter the value for list 2 :23
Enter the value for list 2 :95
Enter the value for list 2 :49
Enter the value for list 2 :327


Concatenated array :  [  3  14  23  23  49  52  52  54  95 327]


 **QUESTION 3 :** 
 
 **Write a code snippet to find the dimensions of a ndarray and its size.**

In [9]:
import numpy as np
arr = np.array([[1,3,5] , [7,9,6] , [2,0,8]])
print("Dimensions of array :" , arr.ndim)
print("Size :" ,arr.size)

Dimensions of array : 2
Size : 9


 **QUESTION 4 :**
 
  **How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims**

In [32]:
import numpy as np

arr = np.arange(int(input()))
print(arr)
print(arr.shape)
print()

row_arr  = arr[np.newaxis]
print("row_arr :" ,row_arr)
print("row_arr shape  : " , row_arr.shape)
print()

col_arr = arr[:, np.newaxis]
print("col_arr :" ,col_arr)
print("col_arr :" , col_arr.shape)

5
[0 1 2 3 4]
(5,)

row_arr : [[0 1 2 3 4]]
row_arr shape  :  (1, 5)

col_arr : [[0]
 [1]
 [2]
 [3]
 [4]]
col_arr : (5, 1)


In [33]:
import numpy as np
arr = np.arange(int(input()))
print(arr.shape)
print()

row_arr = np.expand_dims(arr ,axis=0)
print("row_arr :" ,row_arr)
print("row_arr shape  : " , row_arr.shape)
print()

col_arr = np.expand_dims(arr ,axis=1)
print("col_arr :" ,col_arr)
print("col_arr :" , col_arr.shape)

5
(5,)

row_arr : [[0 1 2 3 4]]
row_arr shape  :  (1, 5)

col_arr : [[0]
 [1]
 [2]
 [3]
 [4]]
col_arr : (5, 1)


 **QUESTION 5 :** 
 
 **Consider two square numpy arrays. Stack them vertically and horizontally.**


**Hint: Use vstack(), hstack()**

In [16]:
import numpy as np
arr_1 = np.square([1,2,3,4,5])
arr_2 = np.square([6,7,8,9,10])

print(np.hstack((arr_1 , arr_2)))
print()
print(np.vstack((arr_1 , arr_2)))

[  1   4   9  16  25  36  49  64  81 100]

[[  1   4   9  16  25]
 [ 36  49  64  81 100]]


 **QUESTION 6 :** 
 
 **How to get unique items and counts of unique items?**

Unique method in numpy is used to get the unique values and return count attribute is used to get the count.

In [26]:
import numpy as np

arr = np.array([1,2,5,1,6,4,6,6,3,14,35,23,42,4,5])

arr_count = np.unique(arr , return_counts=True)

print( np.asarray((arr_count)).T)


[[ 1  2]
 [ 2  1]
 [ 3  1]
 [ 4  2]
 [ 5  2]
 [ 6  3]
 [14  1]
 [23  1]
 [35  1]
 [42  1]]
